name: Team awesome's approval workflow
on:
  workflow_dispatch:
jobs:
  labelWhenApproved:
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
            animal: cat
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      run: echo ${{matrix.color}}
