name: Team awesome's approval workflow
on:
  workflow_dispatch:
jobs:
  labelWhenApproved:
    strategy:
      matrix:
        #fruit: [apple, pear]
        animal: [cat]
        include:
          - color: pink
            animal: cat
          - color: green
            animal: cat
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
