name: Team awesome's approval workflow
on:
  workflow_dispatch:
jobs:
  labelWhenApproved:
    strategy:
      matrix:
        #fruit: [apple, pear]
        animal: [cat]
        include:
          - color: pink
            animal: cat
          - color: green
            animal: cat
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      run: echo "::warning::Missing semicolon"
